#!/usr/bin/env python

import argparse
from collections import defaultdict
from datetime import datetime
import itertools
import struct
import sys
from mmap import mmap
from operator import itemgetter

from util import col_num, col_nums, COL_NAMES, COL_FMT, parse, eval_


def deserialize(rec):
    def tr_str(t):
        return [b.decode('utf-8').rstrip('\0') for b in t]

    def tr_date(i):
        year = i >> 0x9
        month = (i >> 0x5) & 0xf
        day = i & 0x1f
        return [datetime(year, month, day)]

    def tr_rev(i):
        return [float(i)]

    raw = struct.unpack(COL_FMT, rec)
    row = tr_str(raw[0:3]) + tr_date(raw[3]) + tr_rev(raw[4]) + [raw[5]]
    return row


def select(column_info, table, filter_=None, group_by=None, order=None):
    col_order = column_info[0]
    cols = column_info[1:]
    rs = []

    for rec in table:
        row = deserialize(rec)
        if filter_ is None or where(row, filter_):
            rs.append(row)

    if group_by:
        def comparator(row):
            return row[col_num(group_by)]

        groups = []

        for col_val, row_vals in itertools.groupby(
                sorted(rs, key=comparator), comparator):
            row_vals = list(row_vals)
            group = []
            group.append(col_val)
            col_getter = itemgetter(*(col_order))
            for col_n, col in enumerate(col_getter(cols)):
                if callable(col):
                    group.append(col(row_vals))
            groups.append(group)

        return groups

    if order:
        order_by_col_names = order.split(',')
        rs.sort(key=itemgetter(*col_nums(order_by_col_names)))

    col_getter = itemgetter(*(col_order))
    ret_cols = []
    for r in rs:
        c = col_getter(r)
        if len(col_order) == 1:
            ret_cols.append((c,))
        else:
            ret_cols.append(c)
    return ret_cols

def where(row, filter_expr):
    tree = parse(filter_expr, row)
    return eval_(tree)


def from_(mm):
    for i in range(0, len(mm), RECSIZE):
        yield mm[i:i+RECSIZE]


agg_funcs = dict(
    MIN = min,
    MAX = max,
    SUM = sum,
    COUNT = lambda x: len(set(x)),
    COLLECT = lambda x: set(x),
)


def columns(names):
    ret = []
    col_names = names.split(',')
    stripped_col_names = [n.split(':')[0] for n in col_names]
    ret.append(col_nums(stripped_col_names))

    for col_name in COL_NAMES:
        if col_name not in stripped_col_names:
            ret.append(None)
            continue

        name_with_fn = col_names[stripped_col_names.index(col_name)]
        if ':' in name_with_fn:
            col, fn_name = name_with_fn.split(':')
            agg_col_num = col_num(col)

            def agg_func(rows, fn=agg_funcs[fn_name.upper()],
                         agg_col_num=agg_col_num):
                return fn([row[agg_col_num] for row in rows])

            ret.append(agg_func)
        else:
            ret.append(col_name)

    return ret


def format(result):
    acc = []
    for i in result:
        if isinstance(i, datetime):
            acc.append(i.strftime('%Y-%m-%d'))
            continue
        if isinstance(i, float):
            acc.append('{0:.2f}'.format(i))
            continue
        if isinstance(i, str):
            acc.append(i)
            continue
        if isinstance(i, set):
            vals = i
            sub_acc = []
            for v in vals:
                sub_acc.append(v)
            acc += ['[' + ','.join(sub_acc) + ']']
        if isinstance(i, int):
            acc.append(i)

    return ','.join(str(e) for e in acc)



def parse_args(args):
    parser = argparse.ArgumentParser()
    parser.add_argument('-s', '--select', required=True)
    parser.add_argument('-o', '--order')
    parser.add_argument('-f', '--filter')
    parser.add_argument('-g', '--group')
    return parser


if __name__ == '__main__':
    parser = parse_args(sys.argv[1:])
    args = parser.parse_args()
    RECSIZE = 256

    try:
        with open('db.bin', 'r+b') as f, mmap(f.fileno(), 0) as table:
            rs = select(
                columns(args.select), 
                from_(table),
                args.filter,
                args.group,
                args.order,
            )
            for r in rs:
                print(format(r))
    except FileNotFoundError as e:
        print(e, file=sys.stdout)
